### ISSUE TITLE
新版vscode内无法加载模型

### ISSUE THREAD

**Issue by amtoaer** [TheSecondAkari/vscode-live2d#1]
本地vscode版本：1.63.0
修复或可参考：
+ https://github.com/iCharlesZ/vscode-live2d/issues/16
+ https://github.com/iCharlesZ/vscode-live2d/commit/c51f3f08248b36df9c09f83f92e633bd1141f044

**Comment by TheSecondAkari** [comment]
我看看，感谢提供问题和参考

**Comment by TheSecondAkari** [comment]
这个问题我前面注意到了，然后绕过vscode的安全策略使用的是iframe，没有把原来的 [安全策略代码注释掉](https://github.com/iCharlesZ/vscode-live2d/issues/16)。    是其他问题，我处理一下，快修好了。  另外有什么建议的话，可以向我提供（功能或者什么之类的，感谢你的支持）。   说来昨晚asoul一周年的直播实在太好看了 🤤🤤🤤🤤🤤🤤🤤

**Comment by TheSecondAkari** [comment]
修复好了    有点话痨....

**Comment by TheSecondAkari** [comment]
done
