### ISSUE TITLE
背景图加个自定义呗

### ISSUE THREAD

**Issue by ziluxike** [TheSecondAkari/vscode-live2d#4]
然后就是后续有没有珈乐的模型捏

**Comment by TheSecondAkari** [comment]
如果有live2d模型提供的话，可以考虑。 我不会做模型/(ㄒoㄒ)/~~

**Comment by TheSecondAkari** [comment]
暂时背景图自定义是分开的使用另一个插件 A-Soul-background.   暂时不打算合并。  目前也有比较多忙的事（也有新的计划内容：asoul相关的）

**Comment by TheSecondAkari** [comment]
新的计划内容，如果能做成的话，欢迎继续试用（提前画饼）

**Comment by ziluxike** [comment]
好的捏 模型可不可以用这个BV1pQ4y1o7ih 加油捏！！！

**Comment by TheSecondAkari** [comment]
需要模型原作者授权才行。 顺便还需要提供模型文件。

**Comment by ziluxike** [comment]
搞定了，看完直播加班捏🥰

![Uploading IMG_0237.PNG…]()
[https://pan.baidu.com/s/1meEJTB1SK7aBJZEupEdlKA ](url)
提取码：379h

**Comment by TheSecondAkari** [comment]
麻了，你是魔鬼吗？  

另外提一下，up是同意了吗？ 他知道模型会被用作什么地方吗？可能会被大家下载使用。还有一点是：你把这个链接处理一下，让它失效把。 我存好模型了（不会随意传播）

**Comment by ziluxike** [comment]
同意了 可能授权的图片没传上去 导致你没看见 链接你存了就行

**Comment by ziluxike** [comment]
http://www.ziluxike.com/1.png 授权图

**Comment by TheSecondAkari** [comment]
我需要一些时间处理(因为除了加上还要调试)，晚些天加上吧。&nbsp; 我有不少东西忙，但是又有点懒。黄嘉祺，对不起 🧎‍♂️🧎‍♂️🧎‍♂️🧎‍♂️，&nbsp; 晚晚会原谅我的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月27日(星期天) 晚上10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TheSecondAkari/vscode-live2d] 背景图加个自定义呗 (Issue #4)





 
同意了 可能授权的图片没传上去 导致你没看见 链接你存了就行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ziluxike** [comment]
没事捏，你慢慢来，咱也不着急。忙碌的同时也要好好吃饭好好睡觉啊 一个魂

**Comment by TheSecondAkari** [comment]
好好好，🤤🤤🤤🤤。&nbsp; &nbsp;打工人有点难（🧎‍♂️）



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月27日(星期天) 晚上11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TheSecondAkari/vscode-live2d] 背景图加个自定义呗 (Issue #4)





 
没事捏，你慢慢来，咱也不着急。忙碌的同时也要好好吃饭好好睡觉啊 一个魂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
